// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type House struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	HeadOfHouse *string    `json:"head_of_house,omitempty"`
	Students    []*Student `json:"students,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Student struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Age   *int32 `json:"age,omitempty"`
	House *House `json:"house,omitempty"`
}
