// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type House struct {
	ID          string
	FirstName   string
	LastName    string
	HeadOfHouse sql.NullString
}

type Student struct {
	ID        string
	FirstName string
	LastName  string
	Age       sql.NullInt32
	HouseID   sql.NullString
}
