// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateHouse(ctx context.Context, arg CreateHouseParams) (House, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	GetAllHouses(ctx context.Context) ([]House, error)
	GetStudentsByHouse(ctx context.Context, houseID sql.NullString) ([]Student, error)
}

var _ Querier = (*Queries)(nil)
